---
title: "Benchmarks"
output:
  html_document: default
  pdf_document: default
  word_document: default
date: "2026-08-06"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)
library(tidyverse)
library(ggplot2)
library(salmonMSE)
library(here)
library(kableExtra)

# Get SR benchmarks (this file must be sourced to create csv file)

# source(here("98-ExtractMSY.R"))
```

## Benchmarks


```{r benchmarks, echo=FALSE}
BenchFull <- read.csv(file = here("tables", "BenchmarksFull_NatPops.csv"))

kable(BenchFull, 
      caption = "Table 1. Populaton-level benchmarks, with SMAX estimated from the conditioning model", booktabs = TRUE) %>% 
  collapse_rows(columns = 1, valign = "top") %>% 
  kable_styling(full_width = FALSE)

# Alternative
BenchSimple <- read.csv(file = here("tables", "BenchmarksSimple_NatPops.csv"))

kable(BenchSimple, 
      caption = "Table 1. Populaton-level benchmarks", booktabs = TRUE) %>% 
  collapse_rows(columns = 1, valign = "top") %>% 
  kable_styling(full_width = FALSE)

```

```{r habitatCapacity, echo=FALSE}
# Smax_hab <- as.data.frame(
#   read.csv(
#     here("data", "UpperSoGChinook_out_posteriorpredictive.csv"))
#   ) %>% 
#   pivot_longer (
#   cols = starts_with("SMAX_"),
#   names_to = "Benchmark",
#   names_prefix = "SMAX_",
#   values_to = "Value") %>% 
#   select("Stock", "WA", "Benchmark", "Value")



Srep_hab <- as.data.frame(
  read.csv(
    here("data", "UpperSoGChinook_out_posteriorpredictive_NEWWArev.csv"))
)  %>%  select("Stock", "WA", "SREP_median", "SREP_lwr5", "SREP_upr95") %>% 
  rename(Population = "Stock", WatershedArea = "WA", SREP = "SREP_median", 
         lwr = "SREP_lwr5", upr = "SREP_upr95")

colnames(Srep_hab) <- c("Population", "Watershed area (km2)", "SREP", "lower CI", "upper CI")


# Smax_hab <- as.data.frame(
#   read.csv(
#     here("data", "UpperSoGChinook_out_posteriorpredictive_NEWWArev.csv"))
# )  %>%  select("Stock", "WA", "SMAX_median", "SMAX_lwr5", "SMAX_upr95") %>% 
#   rename(Population = "Stock", WatershedArea = "WA", SREP = "SMAX_median", 
#          lwr = "SMAX_lwr5", upr = "SMAX_upr95")
# 
# colnames(Smax_hab) <- c("Population", "Watershed area (km2)", "SMAX", "lower CI", "upper CI")
# 

kable(Srep_hab,
      caption = "Table 2. Integrated accesible watershed-area model estimates of SREP",
      booktabs = TRUE,
      escape = FALSE) %>%
  collapse_rows(columns = 1, valign = "top") %>%
  kable_styling(full_width = FALSE)


```


```{r smax, echo=FALSE}

Smax_hab <- as.data.frame(
  read.csv(
    here("data", "UpperSoGChinook_out_posteriorpredictive_NEWWArev.csv"))) %>% 
  select("Stock", "WA", "SMAX_median", "SMAX_lwr5", "SMAX_upr95") %>% 
  rename(Population = "Stock", WatershedArea = "WA", SMAX = "SMAX_median", 
         lwr = "SMAX_lwr5", upr = "SMAX_upr95") %>% 
  filter(Population %in% c("Adam/Eve", "Nimpkish", "Salmon"))

# Productivity for Cowichan Chinook (= mean prod for Fraser river, 3 stocks)
# (Greenberg et al. in prep, Table S4)
mean_logalpha <- 0.87
logalpha_sig <- 0.23


for(pop in c("Adam", "Woss", "Salmon")){
  pop.prior <- pop
  if(pop=="Adam") pop.prior <- "Adam/Eve"
  if(pop=="Woss") pop.prior <- "Nimpkish"

  data_Smax_prior <- as.data.frame( read.csv(
    here("data", "UpperSoGChinook_out_posteriorpredictive_NEWWArev.csv"))
  # ("data/UpperSoGChinook_out_posteriorpredictive_UPDATEDAWA_Aug18.csv"))
  )
  med_Smax_prior <- data_Smax_prior %>% filter(Stock == pop.prior) %>% pull(SMAX_median)
  mean_Smax_prior <- data_Smax_prior %>% filter(Stock == pop.prior) %>% pull(SMAX_mean)
  logSmax_prior_sd <- data_Smax_prior %>% filter(Stock == pop.prior) %>%
    mutate(sigma=(log(SMAX_upr95)-log(SMAX_median))/2) %>%
    pull(sigma)
  logalpha <- rnorm(2000, mean_logalpha, logalpha_sig)
  logSmax <- rnorm(2000, log(med_Smax_prior), logSmax_prior_sd)
  Srep_prior <-  logalpha * exp(logSmax) # Srep = log(alpha)/beta, beta = 1/Smax  
  med_Srep_prior <- quantile(Srep_prior, prob=0.5)
  lwr_Srep_prior <- quantile(Srep_prior, prob=0.025)
  upr_Srep_prior <- quantile(Srep_prior, prob=0.975)

  
  assign(paste0("medSrep_", pop), med_Srep_prior)
  assign(paste0("lwrSrep_", pop), lwr_Srep_prior)
  assign(paste0("uprSrep_", pop), upr_Srep_prior)

}


# logalpha <- rnorm(2000, mean_logalpha, logalpha_sig)
# logSmax <- rnorm(2000, log(med_Smax_prior), logSmax_prior_sd)
# Srep_prior <-  logalpha * exp(logSmax) # Srep = log(alpha)/beta, beta = 1/Smax
# logSrep_prior_sd <- sd(log(Srep_prior))


Smax_hab$SREP <- round( c(medSrep_Woss, medSrep_Adam, medSrep_Salmon), 0)
Smax_hab$SREPlwr <- round( c(lwrSrep_Woss, lwrSrep_Adam, lwrSrep_Salmon), 0)
Smax_hab$SREPupr <- round( c(uprSrep_Woss, uprSrep_Adam, uprSrep_Salmon), 0)

colnames(Smax_hab) <- c("Population", "Watershed area (km2)", "SMAX", 
                        "lower CI", "upper CI", "SREP", 
                        "lower CI", "upper CI")

kable(Smax_hab,
      caption = "Table 2. Integrated accesible watershed-area model estimates of SMAX and SREP", 
      booktabs = TRUE) %>% 
  collapse_rows(columns = 1, valign = "top") %>% 
  kable_styling(full_width = FALSE)


```

```{r RPs, echo=FALSE}

USR <- as.data.frame(read.csv( here(
  "tables",
  "USR.csv")))

kable(USR,
      caption = "Table 3. Alternative Upper Stock References, USRs", 
      booktabs = TRUE) %>% 
  collapse_rows(columns = 1, valign = "top") %>% 
  kable_styling(full_width = FALSE)

```

